import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: {
        "2xl": "1280px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        bd: {
          green: "#006a4e",
          red: "#f42a41",
        },
        // Memorial Museum palette (july36.gov.bd) — prefixed with `mn-`
        // so they don't clash with the existing primary/secondary/etc.
        "mn-july-red": "#E30613",
        "mn-tertiary-container": "#e2e2e2",
        "mn-tertiary-fixed": "#e2e2e2",
        "mn-secondary-fixed-dim": "#c7c6c6",
        "mn-outline": "#8e9192",
        "mn-error": "#ffb4ab",
        "mn-inverse-surface": "#e2e2e2",
        "mn-on-error-container": "#ffdad6",
        "mn-tertiary-fixed-dim": "#c6c6c7",
        "mn-on-error": "#690005",
        "mn-text-dim": "#A1A1AA",
        "mn-on-secondary": "#303031",
        "mn-surface-variant": "#353535",
        "mn-inverse-on-surface": "#303030",
        "mn-surface-container-high": "#2a2a2a",
        "mn-surface-muted": "#1A1A1A",
        "mn-on-primary-fixed-variant": "#454747",
        "mn-surface-container": "#1f1f1f",
        "mn-surface-container-lowest": "#0e0e0e",
        "mn-on-secondary-container": "#b5b5b5",
        "mn-on-surface": "#e2e2e2",
        "mn-tertiary": "#ffffff",
        "mn-surface-tint": "#c6c6c7",
        "mn-surface-bright": "#393939",
        "mn-on-surface-variant": "#c4c7c8",
        "mn-secondary-fixed": "#e3e2e2",
        "mn-surface-container-highest": "#353535",
        "mn-inverse-primary": "#5d5f5f",
        "mn-on-tertiary-container": "#636565",
        "mn-on-background": "#e2e2e2",
        "mn-border-subtle": "#262626",
        "mn-secondary-container": "#464747",
        "mn-primary-fixed-dim": "#c6c6c7",
        "mn-primary-fixed": "#e2e2e2",
        "mn-primary": "#ffffff",
        "mn-error-container": "#93000a",
        "mn-on-primary-fixed": "#1a1c1c",
        "mn-on-secondary-fixed-variant": "#464747",
        "mn-surface": "#131313",
        "mn-on-tertiary-fixed-variant": "#454747",
        "mn-surface-deep": "#0A0A0A",
        "mn-secondary": "#c7c6c6",
        "mn-surface-container-low": "#1b1b1b",
        "mn-on-tertiary": "#2f3131",
        "mn-on-secondary-fixed": "#1b1c1c",
        "mn-primary-container": "#e2e2e2",
        "mn-surface-dim": "#131313",
        "mn-on-primary-container": "#636565",
        "mn-on-primary": "#2f3131",
        "mn-on-tertiary-fixed": "#1a1c1c",
        "mn-outline-variant": "#444748",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        "mn-margin-mobile": "1.5rem",
        "mn-gutter": "2rem",
        "mn-section-gap": "8rem",
        "mn-margin-desktop": "5rem",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        display: ["var(--font-space-grotesk)", "system-ui", "sans-serif"],
        "mn-label-caps": ["var(--font-jetbrains-mono)", "monospace"],
        "mn-body-lg": ["var(--font-inter)", "system-ui", "sans-serif"],
        "mn-headline-lg-mobile": ["var(--font-eb-garamond)", "serif"],
        "mn-headline-md": ["var(--font-eb-garamond)", "serif"],
        "mn-label-md": ["var(--font-inter)", "system-ui", "sans-serif"],
        "mn-headline-lg": ["var(--font-eb-garamond)", "serif"],
        "mn-headline-display": ["var(--font-eb-garamond)", "serif"],
        "mn-body-md": ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "mn-label-caps": ["0.625rem", { lineHeight: "1rem", letterSpacing: "0.18em" }],
        "mn-label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.18em" }],
        "mn-body-md": ["0.875rem", { lineHeight: "1.5rem" }],
        "mn-body-lg": ["1rem", { lineHeight: "1.75rem" }],
        "mn-headline-md": ["1.5rem", { lineHeight: "2rem" }],
        "mn-headline-lg": ["2.5rem", { lineHeight: "3rem" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
}

export default config
