"""POST /api/v1/report/generate — generate PDF trust report."""
from __future__ import annotations

import io
from datetime import datetime

from fastapi import APIRouter, HTTPException, Request, status
from fastapi.responses import StreamingResponse

from PIL import Image, ImageDraw, ImageFont

from .. import config
from ..ratelimit import get_limiter
from ..services.ai_engine.trust_scorer import score_from_request
from ..schemas import AnalyzeRequest

router = APIRouter(prefix="/api/v1/report", tags=["report"])


def _enforce_rate_limit(request: Request) -> None:
    limiter = get_limiter()
    ip = request.client.host if request.client else "unknown"
    xff = request.headers.get("x-forwarded-for")
    if xff:
        ip = xff.split(",")[0].strip() or ip
    allowed, count = limiter.allow(ip)
    if not allowed:
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail={"error": "rate_limit_exceeded", "ip": ip, "current_count": count},
        )


def _create_pdf_report(data: dict) -> bytes:
    """
    Create a simple PDF report using PIL.
    Returns the PDF as bytes.
    """
    # Create a blank image with white background
    width, height = 800, 1000
    image = Image.new("RGB", (width, height), color="white")
    draw = ImageDraw.Draw(image)

    # Try to load a font, fallback to default
    try:
        font_title = ImageFont.truetype("arial.ttf", 24)
        font_heading = ImageFont.truetype("arial.ttf", 18)
        font_body = ImageFont.truetype("arial.ttf", 14)
    except IOError:
        font_title = ImageFont.load_default()
        font_heading = ImageFont.load_default()
        font_body = ImageFont.load_default()

    y = 20
    # Title
    draw.text((width // 2, y), "Trust Report", fill="black", font=font_title, anchor="mt")
    y += 40

    # Timestamp
    draw.text((width // 2, y), f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
              fill="gray", font=font_body, anchor="mt")
    y += 30

    # Separator
    draw.line([(20, y), (width - 20, y)], fill="gray", width=1)
    y += 20

    # Overall Trust
    trust_score = data.get("trust_score", 0)
    overall_risk = data.get("overall_risk", "unknown")
    draw.text((20, y), f"Overall Trust Score: {trust_score}/100", fill="black", font=font_heading)
    y += 25
    draw.text((20, y), f"Risk Level: {overall_risk.upper()}",
              fill="red" if overall_risk == "high" else "orange" if overall_risk == "medium" else "green",
              font=font_body)
    y += 20

    # Scores
    draw.text((20, y), "Component Scores:", fill="black", font=font_heading)
    y += 25
    bias_score = data.get("bias_score", 0)
    scam_prob = data.get("scam_probability", 0)
    deepfake_score = data.get("deepfake_score", 0)
    draw.text((30, y), f"Bias: {bias_score:.2f}", fill="black", font=font_body)
    y += 20
    draw.text((30, y), f"Scam Probability: {scam_prob:.2f}", fill="black", font=font_body)
    y += 20
    draw.text((30, y), f"Deepfake Score: {deepfake_score:.2f}", fill="black", font=font_body)
    y += 20

    # Claims
    claims = data.get("claims", [])
    if claims:
        y += 10
        draw.line([(20, y), (width - 20, y)], fill="gray", width=1)
        y += 20
        draw.text((20, y), "Claim Analysis:", fill="black", font=font_heading)
        y += 25
        for i, claim in enumerate(claims[:5]):  # Limit to 5 claims
            if y > height - 50:
                break
            claim_text = claim.get("text", "")
            verdict = claim.get("verdict", "unknown")
            confidence = claim.get("confidence", 0)
            rationale = claim.get("rationale", "")
            # Truncate long text
            if len(claim_text) > 80:
                claim_text = claim_text[:77] + "..."
            draw.text((30, y), f"{i+1}. {claim_text}", fill="black", font=font_body)
            y += 18
            draw.text((40, y), f"Verdict: {verdict} (confidence: {confidence:.2f})",
                      fill="blue", font=font_body)
            y += 18
            if rationale:
                # Wrap rationale text
                words = rationale.split()
                line = ""
                for word in words:
                    if len(line + word) < 60:
                        line += word + " "
                    else:
                        draw.text((40, y), line.strip(), fill="darkgreen", font=font_body)
                        y += 15
                        line = word + " "
                if line:
                    draw.text((40, y), line.strip(), fill="darkgreen", font=font_body)
                    y += 15
            y += 10

    # Footer
    y = height - 30
    draw.text((width // 2, y), "Generated by JulyDigonto AI Forensics Engine",
              fill="gray", font=font_body, anchor="mt")

    # Save to bytes
    img_byte_arr = io.BytesIO()
    # Convert to PDF if needed, but PIL can save as PDF
    image.save(img_byte_arr, format="PDF")
    img_byte_arr.seek(0)
    return img_byte_arr.read()


@router.post("/generate", status_code=status.HTTP_200_OK)
async def generate_report(
    request: Request,
    req: AnalyzeRequest,
) -> StreamingResponse:
    _enforce_rate_limit(request)
    # Get the analysis from the trust scorer
    analysis = score_from_request(req)
    # Convert to dict
    data = analysis.dict()
    # Generate PDF
    pdf_bytes = _create_pdf_report(data)
    # Return as streaming response
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=trust_report.pdf"}
    )